module BattleDT where
import Data.DecisionTree
import Player
decideProp = (map (decide tree) unlabeled) == labels where
    tree = build atts dataset



getAIFromTree attacker enemy = (decide tree) test
    where
        tree = build atts dataset
        test = D { dName = "", attributes = [(BattleDT.ap,show (Player.ap attacker)),
            (aiclass,show (Player.playerClass attacker)),
            (playerclass,show (Player.playerClass enemy))]}

ap = A { aName = "ap", possibleValues=["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15"] }
aiclass = A { aName ="aiclass", possibleValues=["Melee","Range", "Magic"] }
playerclass = A { aName ="playerclass", possibleValues=["Melee","Range", "Magic"] }
recommendedatk = A { aName ="recommendedatk", possibleValues=["0","1","2","3"]}

atts = [BattleDT.ap,aiclass,playerclass]

dataset = zip labels unlabeled
labels = ["0","0","0","0","0","0","0","0","0","1","1","2","1","1","2","1","1","2","1","1","2","1","1","2",
            "1","1","2","1","1","2","3","2","3","3","2","3","3","2","3","3","2","3","3","2","3","3","2","3",
            "0","0","0","0","0","0","0","0","0","1","2","1","1","2","1","1","2","1","1","2","1","1","2","1",
            "1","2","1","1","2","1","3","2","3","3","2","3","3","2","3","3","2","3","3","2","3","3","2","3",
            "0","0","0","0","0","0","0","0","0","1","2","1","1","2","1","1","2","1","1","2","1","1","2","1",
            "1","2","1","1","2","1","3","2","3","3","2","3","3","2","3","3","2","3","3","2","3","3","2","3"]

unlabeled =
    [D { dName = "", attributes = [(BattleDT.ap,"0"),
            (aiclass,"Melee"),
            (playerclass,"Melee"),
            (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass, "Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Melee"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Melee"),
        (playerclass, "Range"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Melee"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass,"Range"),
        (playerclass,"Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass, "Range"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Range"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Range"),
        (playerclass, "Magic"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Range"),
        (playerclass, "Melee"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass,"Magic"),
        (playerclass,"Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"0"),
        (aiclass, "Magic"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"1"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"2"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"0")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"3"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"4"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"5"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"6"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"7"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"8"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"9"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"1")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"10"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"11"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"12"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"13"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"14"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Magic"),
        (playerclass, "Magic"),
        (recommendedatk,"3")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Magic"),
        (playerclass, "Melee"),
        (recommendedatk,"2")]},
    D { dName = "", attributes = [(BattleDT.ap,"15"),
        (aiclass,"Magic"),
        (playerclass, "Range"),
        (recommendedatk,"3")]}]
